# Generated by Django 3.2.22 on 2024-08-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='FlashSale_expire_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='FlashSaleOn_date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashsale_price', models.PositiveIntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='store.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='store.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='store.variation')),
            ],
        ),
    ]
