# Generated by Django 3.2.22 on 2024-08-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240806_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flashsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.flashsaleproduct'),
        ),
    ]
