# Generated by Django 3.2.22 on 2024-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20241001_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='flashsale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
