# Generated by Django 3.2.22 on 2024-10-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_flashsaleproduct_flashsale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='flash_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='store.flashsale'),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='store.product'),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
