# Generated by Django 3.2.22 on 2024-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20241002_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
