# Generated by Django 3.2.22 on 2024-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20241003_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupons', to='store.Product'),
        ),
    ]
