# Generated by Django 3.2.22 on 2024-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_coupon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='store.Product'),
        ),
    ]
