# Generated by Django 3.2.22 on 2024-10-03 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_alter_coupon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_user',
            field=models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
