# Generated by Django 3.2.22 on 2024-10-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('On the way', 'On the way'), ('Complete', 'Complete'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='Pending', max_length=150),
        ),
    ]
