# Generated by Django 3.2.22 on 2024-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_roled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
