# Generated by Django 3.2.22 on 2024-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
