# Generated by Django 3.2.22 on 2024-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_merchant_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
