# Generated by Django 3.2.22 on 2024-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_total_shipping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
