# Generated by Django 3.2.22 on 2024-10-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitem_shipping_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='redx_percel_traking_number',
            new_name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='others_transport_trakink_url',
        ),
    ]
