# Generated by Django 3.2.22 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_pathaoparcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathaoparcel',
            name='place_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
