# Generated by Django 3.2.22 on 2024-10-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_pathaoparcel_place_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathaoparcel',
            name='place_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
