# Generated by Django 3.2.22 on 2024-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_pathaoparcel_place_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flash_sale_add_and_expire_date',
        ),
    ]
