# Generated by Django 3.2.22 on 2024-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20241116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pathao_consignment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
