# Generated by Django 3.2.22 on 2024-11-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_pathaoparcel_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathaoparcel',
            old_name='orderItem',
            new_name='order_item',
        ),
    ]
