# Generated by Django 3.2.22 on 2024-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_orderitem_pathaoparcel_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pathao_status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
