# Generated by Django 3.2.22 on 2024-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_orderitem_pathao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pathao_order_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
