# Generated by Django 3.2.22 on 2024-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_pathao_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinformation',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinformation',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinformation',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinformation',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
