# Generated by Django 3.2.22 on 2024-12-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20241205_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='campain-img'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='role_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
