# Generated by Django 3.2.22 on 2024-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingaddress',
            name='shiping_area',
            field=models.CharField(choices=[('Inside Chittagong', 'Inside Chittagong'), ('Outside Chittagong', 'Outside Chittagong')], max_length=100),
        ),
    ]
