# Generated by Django 3.2.22 on 2024-10-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_alter_shipingaddress_shiping_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingaddress',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
