# Generated by Django 3.2.22 on 2024-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_auto_20241014_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingaddress',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
