# Generated by Django 3.2.22 on 2024-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0005_pathaotoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('zone_id', models.IntegerField()),
                ('store_address', models.TextField()),
                ('city_id', models.IntegerField()),
                ('hub_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('is_default_return_store', models.BooleanField()),
                ('is_default_store', models.BooleanField()),
            ],
        ),
    ]
