# Generated by Django 3.2.22 on 2024-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0006_pathaostores'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingaddress',
            name='area_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='city_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='zone_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
