# Generated by Django 3.2.22 on 2025-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0007_auto_20241212_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
            ],
            options={
                'verbose_name': 'Bkash Api',
                'verbose_name_plural': 'Bkash Api',
            },
        ),
    ]
