# Generated by Django 3.2.22 on 2025-05-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0008_bkashapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathaotoken',
            name='access_token',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='pathaotoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
