# Generated by Django 3.2.22 on 2024-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__id', 'user__full_name'), 'verbose_name_plural': 'Customer Profile'},
        ),
    ]
