# Generated by Django 3.2.22 on 2024-07-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='Pending', max_length=150)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('complete_date', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(to='store.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, help_text='Enter your mobile banking phone number for Bkash, Nagad, Rocket, or any other service', max_length=15, null=True, verbose_name='Mobile Banking Phone Number (e.g., Bkash, Nagad, Rocket, or others)')),
                ('phone2', models.CharField(blank=True, help_text='Enter your mobile banking phone number for Bkash, Nagad, Rocket, or any other service', max_length=15, null=True, verbose_name='Mobile Banking Phone Number (e.g., Bkash, Nagad, Rocket, or others)')),
                ('id_type', models.CharField(choices=[('NID', 'NID'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence')], default='NID', max_length=20)),
                ('vendor_image', models.ImageField(blank=True, default='no_img.png', null=True, upload_to='vendor_image/')),
                ('Nid_number', models.CharField(max_length=20)),
                ('NID_copy_1', models.FileField(upload_to='')),
                ('NID_copy_2', models.FileField(upload_to='')),
                ('shop_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('upazila', models.CharField(max_length=20)),
                ('warehouse_address', models.BooleanField(default=True)),
                ('w_address', models.CharField(blank=True, max_length=300, null=True)),
                ('w_division', models.CharField(blank=True, max_length=20, null=True)),
                ('w_district', models.CharField(blank=True, max_length=20, null=True)),
                ('w_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('return_address', models.BooleanField(default=True)),
                ('r_address', models.CharField(blank=True, max_length=300, null=True)),
                ('r_division', models.CharField(blank=True, max_length=20, null=True)),
                ('r_district', models.CharField(blank=True, max_length=20, null=True)),
                ('r_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('account_title', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch_name', models.CharField(max_length=30)),
                ('routing_number', models.CharField(max_length=30)),
                ('cheque_copy', models.FileField(blank=True, null=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendorinformation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendor Profile',
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='other_vendors.district')),
            ],
            options={
                'verbose_name': 'Sub District',
                'verbose_name_plural': 'Sub Districts',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='other_vendors.country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='other_vendors.division'),
        ),
    ]
