# Generated by Django 3.2.22 on 2024-10-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
