# Generated by Django 3.2.22 on 2024-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_vendors', '0002_vendorpayment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor-payment/document'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor-payment/images'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='transaction_informations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
