# Generated by Django 3.2.22 on 2024-10-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_vendors', '0003_auto_20241010_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='store_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
