# Generated by Django 3.2.22 on 2024-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_vendors', '0004_vendorinformation_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorinformation',
            options={'ordering': ('user__email',), 'verbose_name_plural': 'Vendor Profile'},
        ),
    ]
